---
# SPDX-FileCopyrightText: © 2024 Menacit AB <foss@menacit.se>
# SPDX-License-Identifier: CC-BY-SA-4.0
# X-Context: Presentation - HTTP explained - Ignored files for secrets scanning (slides and labs)
paths-ignore:
  - "index.md"
